export const players = [
  {
    name: 'Kavya Agrawal',
    type: 'Batsman',
    battingStyle: 'Right-handed',
    bowlingStyle: 'Right-handed',
    category: 'Legendary',
    playerType: 'male',
    currentPrice: '100000',
    basePrice: '100000',
    isSold: false,
    teamName: null,
    image: '/players-image/no_user.jpg',
  },
  {
    name: 'Aadit Desai',
    type: 'All-rounder',
    battingStyle: 'Right-handed',
    bowlingStyle: 'Right-handed',
    category: 'Legendary',
    playerType: 'male',
    currentPrice: '100000',
    basePrice: '100000',
    isSold: false,
    teamName: null,
    image: '/players-image/no_user.jpg',
  },
  {
    name: 'Vyom Hemang Patel',
    type: 'All-rounder',
    battingStyle: 'Right-handed',
    bowlingStyle: 'Right-handed',
    category: 'Legendary',
    playerType: 'male',
    currentPrice: '100000',
    basePrice: '100000',
    isSold: false,
    teamName: null,
    image: '/players-image/no_user.jpg',
  },
  {
    name: 'Prananya Patel',
    type: 'All-rounder',
    battingStyle: 'Right-handed',
    bowlingStyle: 'Right-handed',
    category: 'Legendary',
    playerType: 'male',
    currentPrice: '100000',
    basePrice: '100000',
    isSold: false,
    teamName: null,
    image: '/players-image/no_user.jpg',
  },
  {
    name: 'Tushar Ashok Sharma',
    type: 'All-rounder',
    battingStyle: 'Right-handed',
    bowlingStyle: 'Right-handed',
    category: 'Legendary',
    playerType: 'male',
    currentPrice: '100000',
    basePrice: '100000',
    isSold: false,
    teamName: null,
    image: '/players-image/no_user.jpg',
  },
  {
    name: 'Keval Tejas Sheth',
    type: 'All-rounder',
    battingStyle: 'Left Handed',
    bowlingStyle: 'Left-handed',
    category: 'Legendary',
    playerType: 'male',
    currentPrice: '100000',
    basePrice: '100000',
    isSold: false,
    teamName: null,
    image: '/players-image/no_user.jpg',
  },
  {
    name: 'Kavya patel',
    type: 'All-rounder',
    battingStyle: 'Right-handed',
    bowlingStyle: 'Right-handed',
    category: 'Legendary',
    playerType: 'male',
    currentPrice: '100000',
    basePrice: '100000',
    isSold: false,
    teamName: null,
    image: '/players-image/no_user.jpg',
  },
  {
    name: 'Virendrasinh Chudasa',
    type: 'Batsman',
    battingStyle: 'Right-handed',
    bowlingStyle: 'Right-handed',
    category: 'Legendary',
    playerType: 'male',
    currentPrice: '100000',
    basePrice: '100000',
    isSold: false,
    teamName: null,
    image: '/players-image/no_user.jpg',
  },
  {
    name: 'Tushil Divyang patel',
    type: 'All-rounder',
    battingStyle: 'Right-handed',
    bowlingStyle: 'Right-handed',
    category: 'Legendary',
    playerType: 'male',
    currentPrice: '100000',
    basePrice: '100000',
    isSold: false,
    teamName: null,
    image: '/players-image/no_user.jpg',
  },
  {
    name: 'Vihan Tripathi',
    type: 'All-rounder',
    battingStyle: 'Right-handed',
    bowlingStyle: 'Right-handed',
    category: 'Legendary',
    playerType: 'male',
    currentPrice: '100000',
    basePrice: '100000',
    isSold: false,
    teamName: null,
    image: '/players-image/no_user.jpg',
  },
  {
    name: 'Ayush Patel',
    type: 'All-rounder',
    battingStyle: 'Right-handed',
    bowlingStyle: 'Right-handed',
    category: 'Legendary',
    playerType: 'male',
    currentPrice: '100000',
    basePrice: '100000',
    isSold: false,
    teamName: null,
    image: '/players-image/no_user.jpg',
  },
  {
    name: 'Anuj Chauhan',
    type: 'Bowler',
    battingStyle: 'Right-handed',
    bowlingStyle: 'Left-handed',
    category: 'Legendary',
    playerType: 'male',
    currentPrice: '100000',
    basePrice: '100000',
    isSold: false,
    teamName: null,
    image: '/players-image/no_user.jpg',
  },
  {
    name: 'Ǫais vohra',
    type: 'All-rounder',
    battingStyle: 'Right-handed',
    bowlingStyle: 'Right-handed',
    category: 'Legendary',
    playerType: 'male',
    currentPrice: '100000',
    basePrice: '100000',
    isSold: false,
    teamName: null,
    image: '/players-image/no_user.jpg',
  },
  {
    name: 'Heth Desai',
    type: 'All-rounder',
    battingStyle: 'Right-handed',
    bowlingStyle: 'Right-handed',
    category: 'Legendary',
    playerType: 'male',
    currentPrice: '100000',
    basePrice: '100000',
    isSold: false,
    teamName: null,
    image: '/players-image/no_user.jpg',
  },
  {
    name: 'Shashwat kothari',
    type: 'All-rounder',
    battingStyle: 'Right-handed',
    bowlingStyle: 'Right-handed',
    category: 'Legendary',
    playerType: 'male',
    currentPrice: '100000',
    basePrice: '100000',
    isSold: false,
    teamName: null,
    image: '/players-image/no_user.jpg',
  },
  {
    name: 'Aarav Khamar',
    type: 'All-rounder',
    battingStyle: 'Right-handed',
    bowlingStyle: 'Right-handed',
    category: 'Legendary',
    playerType: 'male',
    currentPrice: '100000',
    basePrice: '100000',
    isSold: false,
    teamName: null,
    image: '/players-image/no_user.jpg',
  },
  {
    name: 'Daksh patel',
    type: 'All-rounder',
    battingStyle: 'Left Handed',
    bowlingStyle: 'Left-handed',
    category: 'Legendary',
    playerType: 'male',
    currentPrice: '100000',
    basePrice: '100000',
    isSold: false,
    teamName: null,
    image: '/players-image/no_user.jpg',
  },
  {
    name: 'Yagna',
    type: 'All-rounder',
    battingStyle: 'Right-handed',
    bowlingStyle: 'Right-handed',
    category: 'Mastery (Rank 2)',
    playerType: 'male',
    currentPrice: '100000',
    basePrice: '100000',
    isSold: false,
    teamName: null,
    image: '/players-image/no_user.jpg',
  },
  {
    name: 'Prem Tanna',
    type: 'Batsman',
    battingStyle: 'Right-handed',
    bowlingStyle: 'Right-handed',
    category: 'Mastery (Rank 2)',
    playerType: 'male',
    currentPrice: '100000',
    basePrice: '100000',
    isSold: false,
    teamName: null,
    image: '/players-image/no_user.jpg',
  },
  {
    name: 'Heet Hundia',
    type: 'All-rounder',
    battingStyle: 'Right-handed',
    bowlingStyle: 'Right-handed',
    category: 'Mastery (Rank 2)',
    playerType: 'male',
    currentPrice: '100000',
    basePrice: '100000',
    isSold: false,
    teamName: null,
    image: '/players-image/no_user.jpg',
  },
  {
    name: 'SAAD KAZI',
    type: 'Batsman',
    battingStyle: 'Right-handed',
    bowlingStyle: 'Right-handed',
    category: 'Mastery (Rank 2)',
    playerType: 'male',
    currentPrice: '100000',
    basePrice: '100000',
    isSold: false,
    teamName: null,
    image: '/players-image/no_user.jpg',
  },
  {
    name: 'Aditya Patel',
    type: 'All-rounder',
    battingStyle: 'Right-handed',
    bowlingStyle: 'Right-handed',
    category: 'Mastery (Rank 2)',
    playerType: 'male',
    currentPrice: '100000',
    basePrice: '100000',
    isSold: false,
    teamName: null,
    image: '/players-image/no_user.jpg',
  },
  {
    name: 'Harman Bhojwani',
    type: 'All-rounder',
    battingStyle: 'Right-handed',
    bowlingStyle: 'Right-handed',
    category: 'Mastery (Rank 2)',
    playerType: 'male',
    currentPrice: '100000',
    basePrice: '100000',
    isSold: false,
    teamName: null,
    image: '/players-image/no_user.jpg',
  },
  {
    name: 'Tanishq Chintan Joshi',
    type: 'All-rounder',
    battingStyle: 'Right-handed',
    bowlingStyle: 'Right-handed',
    category: 'Mastery (Rank 2)',
    playerType: 'male',
    currentPrice: '100000',
    basePrice: '100000',
    isSold: false,
    teamName: null,
    image: '/players-image/no_user.jpg',
  },
  {
    name: 'Navya Patel',
    type: 'All-rounder',
    battingStyle: 'Right-handed',
    bowlingStyle: 'Right-handed',
    category: 'Mastery (Rank 2)',
    playerType: 'male',
    currentPrice: '100000',
    basePrice: '100000',
    isSold: false,
    teamName: null,
    image: '/players-image/no_user.jpg',
  },
  {
    name: 'Vishal Patel',
    type: 'All-rounder',
    battingStyle: 'Left Handed',
    bowlingStyle: 'Left-handed',
    category: 'Mastery (Rank 2)',
    playerType: 'male',
    currentPrice: '100000',
    basePrice: '100000',
    isSold: false,
    teamName: null,
    image: '/players-image/no_user.jpg',
  },
  {
    name: 'Takshil Madhwani',
    type: 'All-rounder',
    battingStyle: 'Right-handed',
    bowlingStyle: 'Right-handed',
    category: 'Mastery (Rank 2)',
    playerType: 'male',
    currentPrice: '100000',
    basePrice: '100000',
    isSold: false,
    teamName: null,
    image: '/players-image/no_user.jpg',
  },
  {
    name: 'Nihar Mali',
    type: 'All-rounder',
    battingStyle: 'Right-handed',
    bowlingStyle: 'Right-handed',
    category: 'Mastery (Rank 2)',
    playerType: 'male',
    currentPrice: '100000',
    basePrice: '100000',
    isSold: false,
    teamName: null,
    image: '/players-image/no_user.jpg',
  },
  {
    name: 'Daksh Agarwal',
    type: 'All-rounder',
    battingStyle: 'Left Handed',
    bowlingStyle: 'Left-handed',
    category: 'Mastery (Rank 2)',
    playerType: 'male',
    currentPrice: '100000',
    basePrice: '100000',
    isSold: false,
    teamName: null,
    image: '/players-image/no_user.jpg',
  },
  {
    name: 'Akshar Priteshkumar B',
    type: 'All-rounder',
    battingStyle: 'Right-handed',
    bowlingStyle: 'Right-handed',
    category: 'Mastery (Rank 2)',
    playerType: 'male',
    currentPrice: '100000',
    basePrice: '100000',
    isSold: false,
    teamName: null,
    image: '/players-image/no_user.jpg',
  },
  {
    name: 'Mitrav chokshi',
    type: 'All-rounder',
    battingStyle: 'Right-handed',
    bowlingStyle: 'Right-handed',
    category: 'Mastery (Rank 2)',
    playerType: 'male',
    currentPrice: '100000',
    basePrice: '100000',
    isSold: false,
    teamName: null,
    image: '/players-image/no_user.jpg',
  },
  {
    name: 'Kavya ahir',
    type: 'All-rounder',
    battingStyle: 'Left Handed',
    bowlingStyle: 'Left-handed',
    category: 'Mastery (Rank 2)',
    playerType: 'male',
    currentPrice: '100000',
    basePrice: '100000',
    isSold: false,
    teamName: null,
    image: '/players-image/no_user.jpg',
  },
  {
    name: 'Krushank agrawal',
    type: 'All-rounder',
    battingStyle: 'Right-handed',
    bowlingStyle: 'Right-handed',
    category: 'Mastery (Rank 2)',
    playerType: 'male',
    currentPrice: '100000',
    basePrice: '100000',
    isSold: false,
    teamName: null,
    image: '/players-image/no_user.jpg',
  },
  {
    name: 'Raksh',
    type: 'All-rounder',
    battingStyle: 'Right-handed',
    bowlingStyle: 'Right-handed',
    category: 'Mastery (Rank 2)',
    playerType: 'male',
    currentPrice: '100000',
    basePrice: '100000',
    isSold: false,
    teamName: null,
    image: '/players-image/no_user.jpg',
  },
  {
    name: 'Niv Lakhani',
    type: 'All-rounder',
    battingStyle: 'Right-handed',
    bowlingStyle: 'Right-handed',
    category: 'Mastery (Rank 2)',
    playerType: 'male',
    currentPrice: '100000',
    basePrice: '100000',
    isSold: false,
    teamName: null,
    image: '/players-image/no_user.jpg',
  },
  {
    name: 'Dhrumil Thakkar',
    type: 'All-rounder',
    battingStyle: 'Right-handed',
    bowlingStyle: 'Right-handed',
    category: 'Mastery (Rank 2)',
    playerType: 'male',
    currentPrice: '100000',
    basePrice: '100000',
    isSold: false,
    teamName: null,
    image: '/players-image/no_user.jpg',
  },
  {
    name: 'Nihar Patel',
    type: 'Bowler',
    battingStyle: 'Left Handed',
    bowlingStyle: 'Left-handed',
    category: 'Mastery (Rank 2)',
    playerType: 'male',
    currentPrice: '100000',
    basePrice: '100000',
    isSold: false,
    teamName: null,
    image: '/players-image/no_user.jpg',
  },
  {
    name: 'Manthan Datta',
    type: 'Batsman',
    battingStyle: 'Right-handed',
    bowlingStyle: 'Right-handed',
    category: 'Mastery (Rank 2)',
    playerType: 'male',
    currentPrice: '100000',
    basePrice: '100000',
    isSold: false,
    teamName: null,
    image: '/players-image/no_user.jpg',
  },
  {
    name: 'Yash Jirawla',
    type: 'All-rounder',
    battingStyle: 'Left Handed',
    bowlingStyle: 'Left-handed',
    category: 'Mastery (Rank 2)',
    playerType: 'male',
    currentPrice: '100000',
    basePrice: '100000',
    isSold: false,
    teamName: null,
    image: '/players-image/no_user.jpg',
  },
  {
    name: 'Nishchay Vesasi',
    type: 'All-rounder',
    battingStyle: 'Left Handed',
    bowlingStyle: 'Right-handed',
    category: 'Mastery (Rank 2)',
    playerType: 'male',
    currentPrice: '100000',
    basePrice: '100000',
    isSold: false,
    teamName: null,
    image: '/players-image/no_user.jpg',
  },
  {
    name: 'Desai Sahil',
    type: 'All-rounder',
    battingStyle: 'Right-handed',
    bowlingStyle: 'Right-handed',
    category: 'Mastery (Rank 2)',
    playerType: 'male',
    currentPrice: '100000',
    basePrice: '100000',
    isSold: false,
    teamName: null,
    image: '/players-image/no_user.jpg',
  },
  {
    name: 'Haswi Sanjaybhai pate',
    type: 'All-rounder',
    battingStyle: 'Right-handed',
    bowlingStyle: 'Right-handed',
    category: 'Mastery (Rank 2)',
    playerType: 'male',
    currentPrice: '100000',
    basePrice: '100000',
    isSold: false,
    teamName: null,
    image: '/players-image/no_user.jpg',
  },
  {
    name: 'Neeal Dave',
    type: 'All-rounder',
    battingStyle: 'Left Handed',
    bowlingStyle: 'Left-handed',
    category: 'Veteran (Rank 3)',
    playerType: 'male',
    currentPrice: '100000',
    basePrice: '100000',
    isSold: false,
    teamName: null,
    image: '/players-image/no_user.jpg',
  },
  {
    name: 'Aryan Viral Doshi',
    type: 'Batsman',
    battingStyle: 'Right-handed',
    bowlingStyle: 'Right-handed',
    category: 'Veteran (Rank 3)',
    playerType: 'male',
    currentPrice: '100000',
    basePrice: '100000',
    isSold: false,
    teamName: null,
    image: '/players-image/no_user.jpg',
  },
  {
    name: 'Rudra Sharma',
    type: 'All-rounder',
    battingStyle: 'Left Handed',
    bowlingStyle: 'Right-handed',
    category: 'Veteran (Rank 3)',
    playerType: 'male',
    currentPrice: '100000',
    basePrice: '100000',
    isSold: false,
    teamName: null,
    image: '/players-image/no_user.jpg',
  },
  {
    name: 'Supan Harin Shah',
    type: 'Batsman',
    battingStyle: 'Right-handed',
    bowlingStyle: 'Right-handed',
    category: 'Veteran (Rank 3)',
    playerType: 'male',
    currentPrice: '100000',
    basePrice: '100000',
    isSold: false,
    teamName: null,
    image: '/players-image/no_user.jpg',
  },
  {
    name: 'Praksham Sharda',
    type: 'All-rounder',
    battingStyle: 'Left Handed',
    bowlingStyle: 'Right-handed',
    category: 'Veteran (Rank 3)',
    playerType: 'male',
    currentPrice: '100000',
    basePrice: '100000',
    isSold: false,
    teamName: null,
    image: '/players-image/no_user.jpg',
  },
  {
    name: 'Ramit Nitin Savani',
    type: 'Batsman',
    battingStyle: 'Right-handed',
    bowlingStyle: 'Right-handed',
    category: 'Veteran (Rank 3)',
    playerType: 'male',
    currentPrice: '100000',
    basePrice: '100000',
    isSold: false,
    teamName: null,
    image: '/players-image/no_user.jpg',
  },
  {
    name: 'Nakul Harshal Deodha',
    type: 'Batsman',
    battingStyle: 'Right-handed',
    bowlingStyle: 'Right-handed',
    category: 'Veteran (Rank 3)',
    playerType: 'male',
    currentPrice: '100000',
    basePrice: '100000',
    isSold: false,
    teamName: null,
    image: '/players-image/no_user.jpg',
  },
  {
    name: 'Krishiv machhiyava',
    type: 'All-rounder',
    battingStyle: 'Right-handed',
    bowlingStyle: 'Left-handed',
    category: 'Veteran (Rank 3)',
    playerType: 'male',
    currentPrice: '100000',
    basePrice: '100000',
    isSold: false,
    teamName: null,
    image: '/players-image/no_user.jpg',
  },
  {
    name: 'Hemil Patel',
    type: 'Bowler',
    battingStyle: 'Left Handed',
    bowlingStyle: 'Right-handed',
    category: 'Veteran (Rank 3)',
    playerType: 'male',
    currentPrice: '100000',
    basePrice: '100000',
    isSold: false,
    teamName: null,
    image: '/players-image/no_user.jpg',
  },
  {
    name: 'Freya Alpesh Shah',
    type: 'All-rounder',
    battingStyle: 'Left Handed',
    bowlingStyle: 'Right-handed',
    category: 'Veteran (Rank 3)',
    playerType: 'male',
    currentPrice: '100000',
    basePrice: '100000',
    isSold: false,
    teamName: null,
    image: '/players-image/no_user.jpg',
  },
  {
    name: 'Krina kharadi',
    type: 'All-rounder',
    battingStyle: 'Right-handed',
    bowlingStyle: 'Left-handed',
    category: 'Veteran (Rank 3)',
    playerType: 'male',
    currentPrice: '100000',
    basePrice: '100000',
    isSold: false,
    teamName: null,
    image: '/players-image/no_user.jpg',
  },
  {
    name: 'Aryan Shah',
    type: 'All-rounder',
    battingStyle: 'Right-handed',
    bowlingStyle: 'Right-handed',
    category: 'Veteran (Rank 3)',
    playerType: 'male',
    currentPrice: '100000',
    basePrice: '100000',
    isSold: false,
    teamName: null,
    image: '/players-image/no_user.jpg',
  },
  {
    name: 'Dhanya pankaj patel',
    type: 'All-rounder',
    battingStyle: 'Right-handed',
    bowlingStyle: 'Right-handed',
    category: 'Veteran (Rank 3)',
    playerType: 'male',
    currentPrice: '100000',
    basePrice: '100000',
    isSold: false,
    teamName: null,
    image: '/players-image/no_user.jpg',
  },
  {
    name: 'Pratyush sumitbhai su',
    type: 'All-rounder',
    battingStyle: 'Right-handed',
    bowlingStyle: 'Right-handed',
    category: 'Veteran (Rank 3)',
    playerType: 'male',
    currentPrice: '100000',
    basePrice: '100000',
    isSold: false,
    teamName: null,
    image: '/players-image/no_user.jpg',
  },
  {
    name: 'Maurya Shah',
    type: 'All-rounder',
    battingStyle: 'Right-handed',
    bowlingStyle: 'Left-handed',
    category: 'Veteran (Rank 3)',
    playerType: 'male',
    currentPrice: '100000',
    basePrice: '100000',
    isSold: false,
    teamName: null,
    image: '/players-image/no_user.jpg',
  },
  {
    name: 'Karan Niral Pattani',
    type: 'Bowler',
    battingStyle: 'Right-handed',
    bowlingStyle: 'Right-handed',
    category: 'Veteran (Rank 3)',
    playerType: 'male',
    currentPrice: '100000',
    basePrice: '100000',
    isSold: false,
    teamName: null,
    image: '/players-image/no_user.jpg',
  },
  {
    name: 'Aryan motwani',
    type: 'Bowler',
    battingStyle: 'Left Handed',
    bowlingStyle: 'Left-handed',
    category: 'Veteran (Rank 3)',
    playerType: 'male',
    currentPrice: '100000',
    basePrice: '100000',
    isSold: false,
    teamName: null,
    image: '/players-image/no_user.jpg',
  },
  {
    name: 'Krisha kharadi',
    type: 'All-rounder',
    battingStyle: 'Right-handed',
    bowlingStyle: 'Right-handed',
    category: 'Veteran (Rank 3)',
    playerType: 'male',
    currentPrice: '100000',
    basePrice: '100000',
    isSold: false,
    teamName: null,
    image: '/players-image/no_user.jpg',
  },
  {
    name: 'Devarj S. Dave',
    type: 'Bowler',
    battingStyle: 'Right-handed',
    bowlingStyle: 'Right-handed',
    category: 'Veteran (Rank 3)',
    playerType: 'male',
    currentPrice: '100000',
    basePrice: '100000',
    isSold: false,
    teamName: null,
    image: '/players-image/no_user.jpg',
  },
  {
    name: 'Bhavya Meena',
    type: 'All-rounder',
    battingStyle: 'Right-handed',
    bowlingStyle: 'Right-handed',
    category: 'Veteran (Rank 3)',
    playerType: 'male',
    currentPrice: '100000',
    basePrice: '100000',
    isSold: false,
    teamName: null,
    image: '/players-image/no_user.jpg',
  },
  {
    name: 'Rishi Lodhia',
    type: 'Bowler',
    battingStyle: 'Right-handed',
    bowlingStyle: 'Right-handed',
    category: 'Veteran (Rank 3)',
    playerType: 'male',
    currentPrice: '100000',
    basePrice: '100000',
    isSold: false,
    teamName: null,
    image: '/players-image/no_user.jpg',
  },
  {
    name: 'Aditya S. Sejpal',
    type: 'All-rounder',
    battingStyle: 'Right-handed',
    bowlingStyle: 'Right-handed',
    category: 'Veteran (Rank 3)',
    playerType: 'male',
    currentPrice: '100000',
    basePrice: '100000',
    isSold: false,
    teamName: null,
    image: '/players-image/no_user.jpg',
  },
  {
    name: 'Nirmal Anilkumar Pate',
    type: 'All-rounder',
    battingStyle: 'Right-handed',
    bowlingStyle: 'Right-handed',
    category: 'Veteran (Rank 3)',
    playerType: 'male',
    currentPrice: '100000',
    basePrice: '100000',
    isSold: false,
    teamName: null,
    image: '/players-image/no_user.jpg',
  },
  {
    name: 'Fenil patel',
    type: 'All-rounder',
    battingStyle: 'Right-handed',
    bowlingStyle: 'Right-handed',
    category: 'Veteran (Rank 3)',
    playerType: 'male',
    currentPrice: '100000',
    basePrice: '100000',
    isSold: false,
    teamName: null,
    image: '/players-image/no_user.jpg',
  },
  {
    name: 'Mahimna Bhatt',
    type: 'All-rounder',
    battingStyle: 'Right-handed',
    bowlingStyle: 'Right-handed',
    category: 'Veteran (Rank 3)',
    playerType: 'male',
    currentPrice: '100000',
    basePrice: '100000',
    isSold: false,
    teamName: null,
    image: '/players-image/no_user.jpg',
  },
  {
    name: 'Vivek sheth',
    type: 'Bowler',
    battingStyle: 'Right-handed',
    bowlingStyle: 'Left-handed',
    category: 'Veteran (Rank 3)',
    playerType: 'male',
    currentPrice: '100000',
    basePrice: '100000',
    isSold: false,
    teamName: null,
    image: '/players-image/no_user.jpg',
  },
  {
    name: 'Harpit thakkar',
    type: 'All-rounder',
    battingStyle: 'Right-handed',
    bowlingStyle: 'Right-handed',
    category: 'Veteran (Rank 3)',
    playerType: 'male',
    currentPrice: '100000',
    basePrice: '100000',
    isSold: false,
    teamName: null,
    image: '/players-image/no_user.jpg',
  },
  {
    name: 'Ayush Mishra',
    type: 'All-rounder',
    battingStyle: 'Right-handed',
    bowlingStyle: 'Right-handed',
    category: 'Veteran (Rank 3)',
    playerType: 'male',
    currentPrice: '100000',
    basePrice: '100000',
    isSold: false,
    teamName: null,
    image: '/players-image/no_user.jpg',
  },
  {
    name: 'Kashyap Suchak',
    type: 'Batsman',
    battingStyle: 'Right-handed',
    bowlingStyle: 'Right-handed',
    category: 'Veteran (Rank 3)',
    playerType: 'male',
    currentPrice: '100000',
    basePrice: '100000',
    isSold: false,
    teamName: null,
    image: '/players-image/no_user.jpg',
  },
  {
    name: 'Patel Anish Keyurbhai',
    type: 'Bowler',
    battingStyle: 'Right-handed',
    bowlingStyle: 'Right-handed',
    category: 'Veteran (Rank 3)',
    playerType: 'male',
    currentPrice: '100000',
    basePrice: '100000',
    isSold: false,
    teamName: null,
    image: '/players-image/no_user.jpg',
  },
  {
    name: 'Shubham Shah',
    type: 'All-rounder',
    battingStyle: 'Left Handed',
    bowlingStyle: 'Right-handed',
    category: 'Veteran (Rank 3)',
    playerType: 'male',
    currentPrice: '100000',
    basePrice: '100000',
    isSold: false,
    teamName: null,
    image: '/players-image/no_user.jpg',
  },
  {
    name: 'Chaitya Jaldhir Doshi',
    type: 'All-rounder',
    battingStyle: 'Right-handed',
    bowlingStyle: 'Right-handed',
    category: 'Veteran (Rank 3)',
    playerType: 'male',
    currentPrice: '100000',
    basePrice: '100000',
    isSold: false,
    teamName: null,
    image: '/players-image/no_user.jpg',
  },
  {
    name: 'Abhi Vimalkumar Pate',
    type: 'Batsman',
    battingStyle: 'Right-handed',
    bowlingStyle: 'Right-handed',
    category: 'Veteran (Rank 3)',
    playerType: 'male',
    currentPrice: '100000',
    basePrice: '100000',
    isSold: false,
    teamName: null,
    image: '/players-image/no_user.jpg',
  },
  {
    name: 'Dhruvil Desai',
    type: 'All-rounder',
    battingStyle: 'Left Handed',
    bowlingStyle: 'Left-handed',
    category: 'Veteran (Rank 3)',
    playerType: 'male',
    currentPrice: '100000',
    basePrice: '100000',
    isSold: false,
    teamName: null,
    image: '/players-image/no_user.jpg',
  },
  {
    name: 'Naitik Thakkar',
    type: 'Bowler',
    battingStyle: 'Right-handed',
    bowlingStyle: 'Right-handed',
    category: 'Veteran (Rank 3)',
    playerType: 'male',
    currentPrice: '100000',
    basePrice: '100000',
    isSold: false,
    teamName: null,
    image: '/players-image/no_user.jpg',
  },
  {
    name: 'Harshvardhansinh Dab',
    type: 'Batsman',
    battingStyle: 'Left Handed',
    bowlingStyle: 'Left-handed',
    category: 'Veteran (Rank 3)',
    playerType: 'male',
    currentPrice: '100000',
    basePrice: '100000',
    isSold: false,
    teamName: null,
    image: '/players-image/no_user.jpg',
  },
  {
    name: 'Devaarsh Chechani',
    type: 'Bowler',
    battingStyle: 'Right-handed',
    bowlingStyle: 'Right-handed',
    category: 'Veteran (Rank 3)',
    playerType: 'male',
    currentPrice: '100000',
    basePrice: '100000',
    isSold: false,
    teamName: null,
    image: '/players-image/no_user.jpg',
  },
  {
    name: 'Diya Sandip Dubey',
    type: 'Batsman',
    battingStyle: 'Left Handed',
    bowlingStyle: 'Left-handed',
    category: 'Aspirant (Rank 4)',
    playerType: 'male',
    currentPrice: '100000',
    basePrice: '100000',
    isSold: false,
    teamName: null,
    image: '/players-image/no_user.jpg',
  },
  {
    name: 'Dhriti Chaniyara',
    type: 'All-rounder',
    battingStyle: 'Right-handed',
    bowlingStyle: 'Right-handed',
    category: 'Aspirant (Rank 4)',
    playerType: 'male',
    currentPrice: '100000',
    basePrice: '100000',
    isSold: false,
    teamName: null,
    image: '/players-image/no_user.jpg',
  },
  {
    name: 'Parita Shah',
    type: 'Batsman',
    battingStyle: 'Right-handed',
    bowlingStyle: 'No Answer',
    category: 'Aspirant (Rank 4)',
    playerType: 'male',
    currentPrice: '100000',
    basePrice: '100000',
    isSold: false,
    teamName: null,
    image: '/players-image/no_user.jpg',
  },
  {
    name: 'Akshita singhal',
    type: 'All-rounder',
    battingStyle: 'Right-handed',
    bowlingStyle: 'Right-handed',
    category: 'Aspirant (Rank 4)',
    playerType: 'male',
    currentPrice: '100000',
    basePrice: '100000',
    isSold: false,
    teamName: null,
    image: '/players-image/no_user.jpg',
  },
  {
    name: 'Ansh Shah',
    type: 'Bowler',
    battingStyle: 'Left Handed',
    bowlingStyle: 'Right-handed',
    category: 'Aspirant (Rank 4)',
    playerType: 'male',
    currentPrice: '100000',
    basePrice: '100000',
    isSold: false,
    teamName: null,
    image: '/players-image/no_user.jpg',
  },
  {
    name: 'Yashrajsinh Parmar',
    type: 'Batsman',
    battingStyle: 'Right-handed',
    bowlingStyle: 'Right-handed',
    category: 'Aspirant (Rank 4)',
    playerType: 'male',
    currentPrice: '100000',
    basePrice: '100000',
    isSold: false,
    teamName: null,
    image: '/players-image/no_user.jpg',
  },
  {
    name: 'Abhayrajsinh I Gohil',
    type: 'Bowler',
    battingStyle: 'Right-handed',
    bowlingStyle: 'Right-handed',
    category: 'Aspirant (Rank 4)',
    playerType: 'male',
    currentPrice: '100000',
    basePrice: '100000',
    isSold: false,
    teamName: null,
    image: '/players-image/no_user.jpg',
  },
  {
    name: 'Dhyan Shah',
    type: 'Bowler',
    battingStyle: 'Right-handed',
    bowlingStyle: 'Right-handed',
    category: 'Aspirant (Rank 4)',
    playerType: 'male',
    currentPrice: '100000',
    basePrice: '100000',
    isSold: false,
    teamName: null,
    image: '/players-image/no_user.jpg',
  },
  {
    name: 'Kush rank',
    type: 'All-rounder',
    battingStyle: 'Right-handed',
    bowlingStyle: 'Right-handed',
    category: 'Aspirant (Rank 4)',
    playerType: 'male',
    currentPrice: '100000',
    basePrice: '100000',
    isSold: false,
    teamName: null,
    image: '/players-image/no_user.jpg',
  },
  {
    name: 'Dhyana',
    type: 'All-rounder',
    battingStyle: 'Right-handed',
    bowlingStyle: 'Right-handed',
    category: 'Aspirant (Rank 4)',
    playerType: 'male',
    currentPrice: '100000',
    basePrice: '100000',
    isSold: false,
    teamName: null,
    image: '/players-image/no_user.jpg',
  },
  {
    name: 'Shubh Pankitbhai Pate',
    type: 'All-rounder',
    battingStyle: 'Right-handed',
    bowlingStyle: 'Right-handed',
    category: 'Aspirant (Rank 4)',
    playerType: 'male',
    currentPrice: '100000',
    basePrice: '100000',
    isSold: false,
    teamName: null,
    image: '/players-image/no_user.jpg',
  },
  {
    name: 'Pravak Acharya',
    type: 'All-rounder',
    battingStyle: 'Right-handed',
    bowlingStyle: 'Right-handed',
    category: 'Aspirant (Rank 4)',
    playerType: 'male',
    currentPrice: '100000',
    basePrice: '100000',
    isSold: false,
    teamName: null,
    image: '/players-image/no_user.jpg',
  },
  {
    name: 'M Srivatsan',
    type: 'All-rounder',
    battingStyle: 'Right-handed',
    bowlingStyle: 'Right-handed',
    category: 'Aspirant (Rank 4)',
    playerType: 'male',
    currentPrice: '100000',
    basePrice: '100000',
    isSold: false,
    teamName: null,
    image: '/players-image/no_user.jpg',
  },
];

export const categoryOrder = {
  legendary: 'Faculty',
  faculty: 'Mastery',
  mastery: 'Veteran',
  veteran: 'Aspirant',
  aspirant: 'Girls',
  girls: null,
};
